//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uni7ReservasBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controle
    {
        public int Id { get; set; }
        public System.DateTime Abertura { get; set; }
        public System.DateTime Fechamento { get; set; }
        public string ObsBolsista { get; set; }
        public string ObsUsuario { get; set; }
        public SATISFACAO Satisfacao { get; set; }
    
        public virtual Usuario Bolsista { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
