//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uni7ReservasBackend.Models
{
    using System;
    
    public enum TIPOUSUARIO : int
    {
        ADMIN = 0,
        SUPORTE = 1,
        COORDENADOR = 2,
        PROFESSOR = 3
    }
}
